 apiVersion: v1                                                                                                                                                                                                    
  kind: ConfigMap
  metadata:                                                                                                                                                                                                         
    name: expression-test-configmap                                                                                                                                                                               
  data:
    # Fixed Variables (Test 1)
    accountVar: "<+variable.account.gitops_exp_acc_var>"
    orgVar: "<+variable.org.gitops_exp_org_var>"
    projectVar: "<+variable.gitops_exp_proj_var>"

    # Service Variables (Test 2)
    svcStringVar: "<+serviceVariables.stringvar>"
    svcIntVar: "<+serviceVariables.intvar>"
    svcExpressionVar: "<+serviceVariables.expressionvar>"

    # Environment Variables (Test 2)
    envStringVar: "<+env.variables.stringvar>"
    envIntVar: "<+env.variables.intvar>"
    envExpressionVar: "<+env.variables.expressionvar>"

    # Environment Override Test (Test 3)
    envOverrideVar: "<+serviceVariables.envoverriden_var>"
