apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: argocd
data:
  secretfordb: <+variable.account>
  avariable: <+variable.account.a>
